### ISSUE TITLE
Successfully build on Windows 7 & 10

### ISSUE THREAD

**Issue by 0x00A** [voltraco/node-taglib2#5]
$250.00 USD reward

- Needs documented requirements for building on windows 7 and 10
- Needs some reasonable passing and failing tests
- Should be able to require as a dependency from a nodejs project.
- If you want the reward, respond to this issue and I'll assign you.

**Comment by simon-p-r** [comment]
Hey

I am interested on getting this to build.  I can try to add integration with appveyor.

Thanks
Simon

**Comment by 0x00A** [comment]
Excellent! Adding you now.

**Comment by 0x00A** [comment]
@simon-p-r send me an email `admin`, `@voltra.co` so we can arrange compensation info, etc.

**Comment by simon-p-r** [comment]
@0x00A I am not make any promises as very new to c++ :smile:

**Comment by simon-p-r** [comment]
@0x00A I made attempt but am having a problem with the bindings code,  the 2 error shown here on appveyor are as following;

    node-taglib2\src\taglib2.cc(411): error C2440: 'type cast': cannot convert from 'overloaded-function'   to 'node::addon_register_func'
    node-taglib2\src\taglib2.cc(411): error C2440: 'initializing': cannot convert from 'const   char [8]' to 'node::addon_context_register_func' 

https://ci.appveyor.com/project/simon-p-r/node-taglib2/build/1.0.4/job/rv7b82u0epl30b79

My fork of changes is here on this branch https://github.com/simon-p-r/node-taglib2/tree/windows-build

**Comment by 0x00A** [comment]
Looks like you don't have the latest nan? not sure, can you post more of the stack trace?

**Comment by simon-p-r** [comment]
Yes nan version is 2.4, here is a link to coomplete stack trace

https://gist.github.com/simon-p-r/50dd46aeb54e834a5b4198bf7335991d

**Comment by 0x00A** [comment]
Oh, haha, you have 38 errors less than i did :) I'm not sure though, maybe @rvagg can tell us, i think he has some experience with windows people who use nan?

**Comment by bobek-balinek** [comment]
Is it too late to contribute? I have successfully built this library in win32/64 for both node and electron runtimes after a lot of trail & error. I'm happy to share my fork once I have cleaned up all the changes.

**Comment by simon-p-r** [comment]
👏

**Comment by 0x00A** [comment]
@bobek-balinek 👍 this is great! Happy to send you the reward as well :)

**Comment by 0x00A** [comment]
@bobek-balinek Added you as a collaborator to the repo -- https://github.com/voltraco/node-taglib2/invitations

**Comment by bobek-balinek** [comment]
Thank you @0x00A! Just a quick question, is there any specific reason the taglib2 source is at that revision?

**Comment by 0x00A** [comment]
@bobek-balinek that was the last time that i pulled from the upstream project. That revision comes from the `taglib2` branch (not master). From what I understand, there are some design decisions that have yet to be made. That project moves pretty slowly from what i've seen. And tbqh, i've been avoiding it because it's somewhat of a monster. However, it's possible that a more recent revision could work perfectly fine.

**Comment by bobek-balinek** [comment]
OK, the way I've set this up is to use [ExternalProject](https://cmake.org/cmake/help/v3.2/module/ExternalProject.html) module within the CMakeLists.txt file to pull directly from taglib's git repository rather than to contain the source code within the project's code. This feels much cleaner as we can still use the revision IDs to checkout the source at a specific point.

A more recent codebase from the taglib2 branch builds just fine and the tests are passing without a problem. I'm happy to write some more just to be absolutely sure it all works?

**Comment by 0x00A** [comment]
🎉 awesome! 🎉 Yeah, ExternalProject seems like the way to go, this was my first experience with CMake, so it probably wasn't set up very well. Anyway, the more tests the better :) I can test on ubuntu and macos when you are ready.

**Comment by bobek-balinek** [comment]
Here you go: https://github.com/voltraco/node-taglib2/pull/6 😊

**Comment by 0x00A** [comment]
@bobek-balinek hmm, interesting, it seems to sometimes pass and sometimes fail! https://ci.appveyor.com/project/0x00A/node-taglib2/history

**Comment by bobek-balinek** [comment]
Yeah I've seen this. It's the assertion of the BPM value. It happens also on the macOS if you run the test suite more than once (the sample MP3 file gets changed after each test suite)

**Comment by bobek-balinek** [comment]
Would you like me to further investigate the randomly failing test or are we good to close this issue?

I have just ported my electron app that uses this library onto Windows (x64) and everything works great so far. I might submit another pull request to allow a more explicit configuration of `electron` and `architecture` versions when running the `npm install` command.

**Comment by 0x00A** [comment]
Oh cool, what app are you working on? Ideally we'd close out this issue without any known problems. I'd say as soon as that is solved we could close this.

**Comment by bobek-balinek** [comment]
No worries, I'll look into it now.

**Comment by bobek-balinek** [comment]
@0x00A Is there any reason to parse the BPM string value with specific Latin1 encoding? This seems to be what's causing the issue. I've built a UTF-8 version and the issue has disappeared.

```cpp
if (map.contains("BPM")) {
    TagLib::String sl = map["BPM"].toString("");
    TagLib::ByteVector vec = sl.data(TagLib::String::Latin1);
    char* s = vec.data();

   // …
}
```

**Comment by 0x00A** [comment]
I was using Latin1 for song titles, but for bpm UTF-8 should be perfectly fine. If that passes CI, we can call it done! :D

**Comment by bobek-balinek** [comment]
Awesome, I'm submitting a PR then.

Also I've just notice another issue (https://github.com/voltraco/node-taglib2/issues/3) which is likely to be resolved too. When working on the Travis build I have also noticed this issue happening on Ubuntu and have fixed it with passing the `fPIC` flag to TagLib's ExternalProject definition: https://github.com/voltraco/node-taglib2/blob/master/CMakeLists.txt#L44

**Comment by bobek-balinek** [comment]
All looks good, can you bump the version and `npm publish`? 

Also, do I still get the reward? 😊

**Comment by 0x00A** [comment]
Published! We now have version `2.6.0`. Also, let me know if someone hasn't contacted you yet and I'll follow up.

**Comment by 0x00A** [comment]
Hey @bobek-balinek, im getting a strange stack trace on windows, any idea why?

%1 is not a valid Win32 application.\r\n\\\\?\\C:\\work\\voltra\\node_modules\\taglib2\\build\\Release\\taglib2.node

Error: %1 is not a valid Win32 application.\r\n\\\\?\\C:\\work\\voltra\\node_modules\\taglib2\\build\\Release\\taglib2.node\n    at Error (native)\n    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:178:20)\n    at Object.Module._extensions..node (module.js:583:18)\n    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:178:20)\n    at Module.load (module.js:473:32)\n    at tryModuleLoad (module.js:432:12)\n    at Function.Module._load (module.js:424:3)\n    at Module.require (module.js:483:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (C:\\work\\voltra\\node_modules\\taglib2\\index.js:1:97)
```

**Comment by 0x00A** [comment]
Ah, got it figured out, kinda. Not sure what versions of electron and node work together for native builds on windows, but i found that sticking to 32 bit on windows got a successful build.

**Comment by bobek-balinek** [comment]
Ah, I've had that error too. Basically make sure you're using a command line with 64bit version of Visual Studio tools in the %PATH%. I believe there are different shortcuts in Start menu for different versions of CMD with Visual Studio.

**Comment by bobek-balinek** [comment]
Also, did you try running your Electron app on a Windows machine without Visual Studio installed? Please let me know as I'm having some linking troubled with the `taglib.node`.

**Comment by 0x00A** [comment]
Hmm, yeah, i have Win10 x64 (as reported in the settings panel). Both node and electron report `process.arch === 'x64'`. and we are passing `-a ia64` to cmake. So I wonder what it think is still 32bit?!

**Comment by simon-p-r** [comment]
Maybe try -a x64 for cmake

**Comment by bobek-balinek** [comment]
Yeah it should be `x64` or `ia32`. My bad, I must have had a cached version when changing the value and thought it worked.
