### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by adimkov** [voltraco/node-taglib2#8]
Hi folks,

I'm not strong in C++, so sorry for stupid question :)

I compiled library, but i could not able to import it into project. I'm trying to build electron app, and during import i see this error:

```
module.js:583
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\Anton\Documents\Source\coverretriever\node_modules\taglib2\build\Release\taglib2.node
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Anton\Documents\Source\coverretriever\node_modules\taglib2\index.js:1:80)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```
I thought that also i need build taglib (1.11.1) library itself, but it did not help. Let me know if you need more info.

**Comment by 0x00A** [comment]
can you paste the output of `npm install taglib2`? Also, what version of windows are you on?

**Comment by adimkov** [comment]
Hello @0x00A
[log.txt](https://github.com/voltraco/node-taglib2/files/643873/log.txt)
Windows 10 x64

**Comment by 0x00A** [comment]
Can you do ls on `\Users\Anton\Documents\Source\coverretriever\node_modules\taglib2\build\`?

**Comment by adimkov** [comment]
sure.
[build.txt](https://github.com/voltraco/node-taglib2/files/648740/build.txt)

Also i packed build directory, in case if it help
[build.zip](https://github.com/voltraco/node-taglib2/files/648736/build.zip)

**Comment by adimkov** [comment]
Hello Paolo,

Any update?

**Comment by 0x00A** [comment]
We've had terrible luck with windows so far, we're looking to hire someone who has some windows skills :)

**Comment by 0x00A** [comment]
This should be fixed in windows now.
